name: Economy
version: '${project.version}'
main: me.bixgamer707.economy.Economy
api-version: 1.13
authors: [ bixgamer707 ]
description: A economy plugin of the ThunderMC
website: http://discord.thunderloots.xyz
